name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
    - name: Install 1.18 version
      run: |
        go install golang.org/dl/go1.18rc1@latest
        go1.18rc1 download
        cp $(which go1.18rc1) $(which go)
        go version
    - name: Get dependencies
      run: go install
    - name: test
      run: go test -v ./...
